### ISSUE TITLE
Schriftlicher Bericht

### ISSUE THREAD

**Issue by lukasreber** [eugencuic/FHNW_HS20_IRIS_Centroid_Browser#15]
Schriftlicher Bericht im Rahmen von 20 Seiten mit kurzer Einführung, Beschreibung der Software-Architektur und des ganzen Weges von den Requirements bis zur laufenden Software, kurzer Dokumentation des Frontends und der Schnittstellen. Kurze Beschreibung des Entwicklungsprozesses und des Continuous Integration und Continuous Delivery Setups.

**Comment by lukasreber** [comment]
Grundgerüst für den Bericht erstellt und in unserem Teams Kanal abgelegt

**Comment by lukasreber** [comment]
Ist begonnen

**Comment by eugencuic** [comment]
ist beendet
