### ISSUE TITLE
User und Password für Postgres definieren und einstellen

### ISSUE THREAD

**Issue by eugencuic** [eugencuic/FHNW_HS20_IRIS_Centroid_Browser#25]
Momentan ist der User als IRIS mit dem Passwort im Code vorhanden.
Zukünftig sollte der lokale user mit dem Passwort hinterlegt sein, so dass auf die DB zugegriffen werden kann.

sobald alles eingestellt ist sollte der code verändert werden.

**Comment by eugencuic** [comment]
Der neue user und das passwort sind im code verankert, getestet und für OK befunden worden.

Da die tests im moment von einer externen machine auf den server laufen, muss zum schluss noch die IP adresse auf localhost umgeändert werden

**Comment by ChristopherFrame** [comment]
Done!
