### ISSUE TITLE
entferne den ordner centroid_webapp/centroid_webapp

### ISSUE THREAD

**Issue by eugencuic** [eugencuic/FHNW_HS20_IRIS_Centroid_Browser#26]
der ordner ist ein artefakt, dass durch lokale test womöglich übrig geblieben ist und entfernt werden sollte. 

bitte alle diesen ordner aus dem repo entfernen

**Comment by lukasreber** [comment]
sollte der nicht verschwinden, sobald dein branch mit dem master gemerged ist?

**Comment by eugencuic** [comment]
erledigt mit dem pull request
