### ISSUE TITLE
Datenextraktion

### ISSUE THREAD

**Issue by lukasreber** [eugencuic/FHNW_HS20_IRIS_Centroid_Browser#4]
Zumindest ein Teil der Daten befinden sich in der neuen DB auf der VM. Es sind noch nicht zwingend alle Daten erforderlich.

**Comment by lukasreber** [comment]
Ist für V1 umgesetzt. Noch ausstehend sind die Bilder welche für V2 benötigt werden

**Comment by ChristopherFrame** [comment]
Done!
