### ISSUE TITLE
Datenabruf definiert und in Website eingebaut 

### ISSUE THREAD

**Issue by lukasreber** [eugencuic/FHNW_HS20_IRIS_Centroid_Browser#9]
Queries sind definiert. Daten können auf der Website angezeigt werden.

**Comment by eugencuic** [comment]
Die Datenabrufe funktionieren so weit. Im Moment ist es möglich alle Daten aus der DB (lokaler Teilausschnitt) aus der DB zu holen. 
Die Abrufe sind in der Webseite so weit eingebaut und können dargestellt werden.
Die Darstellung der Daten ist so weit noch nicht sauber und wird in den nächsten Schritten verfeinert

**Comment by lukasreber** [comment]
ist erledigt
